= Conclusiones

La elaboración de la arquitectura genérica del sistema clínico OmVital Physio Control permitió capturar y estructurar la dimensión estática del software, traduciendo las políticas asistenciales y administrativas de la clínica de fisioterapia en una organización conceptual de componentes y relaciones. Mediante la aplicación de los principios de abstracción arquitectónica y trazabilidad de requisitos, se logró articular la interacción entre los usuarios operativos, los módulos internos y los servicios externos, estableciendo una base sólida para las posteriores decisiones de diseño y construcción del software.

== Del marco conceptual

- El diseño de una arquitectura genérica permite representar de manera estructurada las principales responsabilidades de un sistema de software, proporcionando una visión general de sus componentes y de las relaciones existentes entre ellos. Esta representación facilita comprender el funcionamiento global del sistema antes de tomar decisiones relacionadas con tecnologías específicas de implementación.
- Se concluye que la arquitectura de software debe construirse a partir de las necesidades y responsabilidades que debe cubrir el sistema, y no únicamente a partir de las herramientas o lenguajes de programación disponibles. Esto permite obtener un diseño más independiente de la tecnología y facilita la evaluación de diferentes alternativas para etapas posteriores del desarrollo.
- La revisión del estado del arte permitió identificar que los sistemas de información en el ámbito de la salud requieren considerar características de calidad como seguridad, privacidad, disponibilidad, integridad, interoperabilidad y mantenibilidad. Estas características tienen una influencia directa sobre las decisiones arquitectónicas y deben ser consideradas desde las primeras etapas del diseño.
- La separación de responsabilidades constituye un principio importante para obtener una arquitectura organizada. Al distribuir las responsabilidades entre diferentes componentes, se puede reducir el acoplamiento y facilitar la comprensión, modificación y mantenimiento del sistema, evitando concentrar todas las funciones en un único componente.
- Se concluye que los requisitos funcionales y no funcionales tienen una relación directa con la arquitectura del sistema. Mientras los requisitos funcionales permiten identificar qué servicios y procesos debe soportar el sistema, los requisitos no funcionales permiten determinar características de calidad que condicionan la forma en que dichos servicios deben ser organizados.
- La interoperabilidad representa una consideración importante dentro de la arquitectura de los sistemas de información en salud. Aunque el sistema propuesto pueda funcionar inicialmente de manera independiente, diseñarlo considerando posibles mecanismos de integración permite establecer una base que pueda adaptarse a futuras necesidades de comunicación con otros sistemas o servicios.
- El análisis de diferentes propuestas y patrones arquitectónicos permite comprender que no existe una única arquitectura que pueda aplicarse de manera general a todos los sistemas. La elección de una alternativa debe responder al contexto, alcance, requisitos y características específicas del sistema que se está diseñando.
- Mantener un nivel adecuado de abstracción durante la construcción de una arquitectura genérica permite concentrarse en las responsabilidades principales del sistema sin introducir prematuramente detalles de implementación, facilitando que el modelo pueda ser utilizado posteriormente como base para tomar decisiones tecnológicas más específicas.

== Del producto

- Se construyó el artefacto técnico en dos niveles de granularidad: una vista general de fronteras (_D-ARQ-001_, Nivel 1) que sintetiza la organización del sistema en subsistemas de Pacientes y Administración, y una vista de despliegue y acceso multi-sucursal (_D-DP-001_, Nivel 2) que expone la topología de infraestructura sobre la nube.
- El modelo elaborado plasma con exactitud la organización de los módulos arquitectónicos del sistema (Pacientes, Citas y Atenciones, Recursos, Documentos y Evaluaciones, API y control de acceso y Plataforma de datos), contemplando la relación con los servicios externos de firma, mensajería y finanzas.
- Se garantizó la trazabilidad directa entre los componentes arquitectónicos y el catálogo de requisitos del proyecto, respaldada en las matrices de educción (`EDU-0001`, `EDU-0002`, `EDU-0005`, `EDU-0006`, `EDU-0025`, `EDU-0026`, `EDU-0029`, `EDU-0031`, `EDU-0032`, `EDU-0033`), ilación (`ILA-0001` a `ILA-0027`) y especificación técnica (`ESP-0001` a `ESP-0043`).
- El artefacto vincula explícitamente los componentes con los requisitos no funcionales del sistema, destacando la disponibilidad de los documentos en la nube (_RNF-0001_), el tiempo de respuesta en la búsqueda por DNI (_RNF-0002_), la captura segura de la firma digital (_RNF-0003_), la actualización en tiempo real de camillas (_RNF-0006_), la emisión de constancias (_RNF-0007_) y la inalterabilidad del consentimiento informado (_RNF-0010_).
- El producto desarrollado mantiene un nivel de abstracción independiente de la tecnología, evitando depender directamente de un lenguaje de programación o plataforma específica. Esto permite que el modelo pueda utilizarse posteriormente como referencia para evaluar y seleccionar las tecnologías más apropiadas.
- El diagrama de arquitectura genérica de Nivel 2 sirve como especificación directriz para las etapas posteriores del proyecto (vista lógica, vista de procesos y despliegue), minimizando desalineaciones entre las necesidades de la clínica y la implementación final del software.