= Conclusiones

La elaboración de la arquitectura genérica del sistema clínico permitió consolidar los conocimientos relacionados con el diseño arquitectónico de software y su aplicación a un sistema orientado al ámbito de la fisioterapia. A partir de los requisitos y resultados obtenidos en las etapas previas, se analizaron las principales responsabilidades del sistema, identificando los componentes necesarios y las relaciones que deben existir entre ellos para proporcionar una estructura organizada y coherente.

== Del marco conceptual

- El diseño de una arquitectura genérica permite representar de manera estructurada las principales responsabilidades de un sistema de software, proporcionando una visión general de sus componentes y de las relaciones existentes entre ellos. Esta representación facilita comprender el funcionamiento global del sistema antes de tomar decisiones relacionadas con tecnologías específicas de implementación.
- Se concluye que la arquitectura de software debe construirse a partir de las necesidades y responsabilidades que debe cubrir el sistema, y no únicamente a partir de las herramientas o lenguajes de programación disponibles. Esto permite obtener un diseño más independiente de la tecnología y facilita la evaluación de diferentes alternativas para etapas posteriores del desarrollo.
- La revisión del estado del arte permitió identificar que los sistemas de información en el ámbito de la salud requieren considerar características de calidad como seguridad, privacidad, disponibilidad, integridad, interoperabilidad y mantenibilidad. Estas características tienen una influencia directa sobre las decisiones arquitectónicas y deben ser consideradas desde las primeras etapas del diseño.
- La separación de responsabilidades constituye un principio importante para obtener una arquitectura organizada. Al distribuir las responsabilidades entre diferentes componentes, se puede reducir el acoplamiento y facilitar la comprensión, modificación y mantenimiento del sistema, evitando concentrar todas las funciones en un único componente.
- Se concluye que los requisitos funcionales y no funcionales tienen una relación directa con la arquitectura del sistema. Mientras los requisitos funcionales permiten identificar qué servicios y procesos debe soportar el sistema, los requisitos no funcionales permiten determinar características de calidad que condicionan la forma en que dichos servicios deben ser organizados.
- En el contexto de un sistema clínico, la arquitectura debe considerar especialmente la protección de la información, debido a que se trabaja con datos relacionados con pacientes y procesos de atención. Por ello, aspectos como el control de acceso, la integridad de la información y la privacidad deben ser contemplados como parte de las decisiones de diseño y no como elementos que se incorporen únicamente durante la implementación.
- La interoperabilidad representa una consideración importante dentro de la arquitectura de los sistemas de información en salud. Aunque el sistema propuesto pueda funcionar inicialmente de manera independiente, diseñarlo considerando posibles mecanismos de integración permite establecer una base que pueda adaptarse a futuras necesidades de comunicación con otros sistemas o servicios.
- El análisis de diferentes propuestas y patrones arquitectónicos permite comprender que no existe una única arquitectura que pueda aplicarse de manera general a todos los sistemas. La elección de una alternativa debe responder al contexto, alcance, requisitos y características específicas del sistema que se está diseñando.
- Se concluye que mantener un nivel adecuado de abstracción durante la construcción de una arquitectura genérica permite concentrarse en las responsabilidades principales del sistema sin introducir prematuramente detalles de implementación. Esto facilita que el modelo pueda ser utilizado posteriormente como base para tomar decisiones tecnológicas más específicas.
- Finalmente, el diseño arquitectónico constituye un vínculo entre los requisitos del sistema y una futura solución de software. Una arquitectura correctamente estructurada permite transformar las necesidades identificadas durante el análisis en una organización lógica de componentes, proporcionando una base para las siguientes actividades de diseño, desarrollo y evolución del sistema.

== Del producto

- Como resultado del trabajo realizado, se logró construir una arquitectura genérica para el sistema clínico orientado a una clínica de fisioterapia, representando de manera general los principales componentes que conforman la solución y las relaciones existentes entre ellos.
- El producto desarrollado permite obtener una visión global de la estructura del sistema, facilitando la identificación de las responsabilidades que deben ser atendidas y la forma en que estas se relacionan para proporcionar los servicios requeridos por la clínica.
- La arquitectura elaborada toma como punto de partida los resultados obtenidos en las etapas previas de Educción, Ilación y Especificación, permitiendo utilizar la información previamente analizada como base para organizar las responsabilidades y construir una representación arquitectónica del sistema.
- El artefacto obtenido permite establecer una correspondencia entre las necesidades identificadas en el sistema clínico y los componentes que deberán participar en su solución. De esta manera, la arquitectura no se presenta como un conjunto aislado de elementos, sino como una representación derivada de los requerimientos previamente establecidos.
- La arquitectura propuesta permite visualizar cómo pueden organizarse las diferentes responsabilidades del sistema clínico, proporcionando una estructura que facilita el análisis de los procesos relacionados con la gestión de pacientes, atención, citas, tratamientos y demás información necesaria para el funcionamiento de la clínica.
- El producto desarrollado mantiene un nivel de abstracción adecuado para una arquitectura genérica, evitando depender directamente de una tecnología, lenguaje de programación o plataforma específica. Esto permite que el modelo pueda utilizarse posteriormente como referencia para evaluar y seleccionar las tecnologías más apropiadas.
- La arquitectura obtenida proporciona una base para considerar los requisitos no funcionales identificados para el sistema. Aspectos como la seguridad, mantenibilidad, disponibilidad e interoperabilidad pueden ser considerados posteriormente en decisiones de diseño más detalladas, sin necesidad de modificar completamente la estructura conceptual obtenida.
- El desarrollo del artefacto permitió identificar la importancia de establecer relaciones claras entre los componentes. Una arquitectura no solamente debe mostrar qué componentes existen, sino también representar cómo estos se relacionan y qué responsabilidades corresponden a cada uno, evitando ambigüedades en la interpretación del diseño.
- El producto obtenido puede utilizarse como referencia para las siguientes etapas del proyecto, ya que proporciona una estructura inicial sobre la cual podrían definirse posteriormente aspectos más específicos de diseño, tecnologías, bases de datos, interfaces, mecanismos de comunicación y estrategias de implementación.
- Finalmente, la arquitectura genérica desarrollada constituye una representación organizada de la solución propuesta para el sistema clínico de fisioterapia. El artefacto permite comunicar de manera más clara la estructura conceptual del sistema y proporciona una base para continuar con el desarrollo del diseño arquitectónico, manteniendo la posibilidad de realizar ajustes conforme se definan con mayor precisión las necesidades técnicas y funcionales del proyecto.